### ISSUE TITLE
Raw strings do not work

### ISSUE THREAD

**Issue by markasoftware** [AmethystGear/JACL#1]
```
port = 31415
data = [{
    "hello" = "hello"
    "there" = r'hi'
    "my" = 82
}]
```

https://github.com/AmethystGear/JACL/blob/12d341fc8d9c61da62fad2d350473d5fa803e056/jaclparser.py#L94

but the regex expects additional quotes (`r'"hi"'`, I think), and there is no code to handle if the scan call returns `None`.

**Comment by markasoftware** [comment]
nevermind, i am the big dumb, double quotes exist

**Comment by AmethystGear** [comment]
lol yeah json uses double quotes for normal strings, I stuck with that for multiline/raw strings as well.
